In [1]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

In [2]:
imports = pd.read_csv('Imports_WITS.csv')
coutry_codes=pd.read_excel('country_code.xlsx')
a_1995 = pd.read_excel('analysis_1995.xlsx', sheet_name='1995')
a_2000 = pd.read_excel('analysis_2000.xlsx', sheet_name='2000')
a_2005 = pd.read_excel('analysis_2005.xlsx', sheet_name='2005')
a_2010 = pd.read_excel('analysis_2010.xlsx', sheet_name='2010')
a_2015 = pd.read_excel('analysis_2015.xlsx', sheet_name='2015')
a_2017 = pd.read_excel('analysis_2017.xlsx', sheet_name='2017')

In [3]:
a_1995['trade_value'] = a_1995['Agree']
a_2000['trade_value'] = a_2000['Agree']
a_2005['trade_value'] = a_2005['Agree']
a_2010['trade_value'] = a_2010['Agree']
a_2015['trade_value'] = a_2015['Agree']
a_2017['trade_value'] = a_2017['Agree']

In [4]:
c_code = coutry_codes['Numeric']
c_num = coutry_codes['3_letter']
rename_df2 = pd.DataFrame({'c_code':c_code, 'c_num':c_num})
iso_dict = rename_df2.set_index('c_num').to_dict()['c_code']

In [5]:
imports_1 = imports.replace({'ReporterISO3': iso_dict, 'PartnerISO3': iso_dict})
imports_1.head(2)

,ReporterISO3,ProductCode,PartnerISO3,Year,TradeFlowCode,TradeValue in 1000 USD
0,784,Total,533,2010,5,168.407
1,784,Total,533,2015,5,0.027

In [6]:
imports_1 = imports_1[imports_1['PartnerISO3']!='ANT']

In [7]:
ReporterISO3 = imports_1.ReporterISO3.values
PartnerISO3 = imports_1.PartnerISO3.values
merged_list = list(zip(PartnerISO3, ReporterISO3))
imports_1['pairs'] = merged_list
imports_1['pairs'] = (imports_1['pairs'].apply(str)).values
imports_1.rename(columns={'TradeValue in 1000 USD':'trade_value'},inplace=True)
imports_1.head(5)

,ReporterISO3,ProductCode,PartnerISO3,Year,TradeFlowCode,trade_value,pairs
0,784,Total,533,2010,5,168.407,"(533, 784)"
1,784,Total,533,2015,5,0.027,"(533, 784)"
2,784,Total,533,2017,5,538.981,"(533, 784)"
3,784,Total,4,2000,5,1322.391,"(4, 784)"
4,784,Total,4,2005,5,3221.568,"(4, 784)"

In [8]:
pairs_95 = imports_1[imports_1['Year']==1995]['pairs']
trade_value_95 = imports_1[imports_1['Year']==1995]['trade_value']
trade_value_df95 = pd.DataFrame({'pairs':pairs_95, 'trade_value':trade_value_95})
trade_value_dict95 = trade_value_df95.set_index('pairs').to_dict()['trade_value']

a_1995 = a_1995.replace({'trade_value': trade_value_dict95})
a_1995.head(5)

,Year,code_dest,code_orig,Continent org,Popn des,Popn org,GDP_PPP des,GDP_PPP org,Distance,Emp rate des,...,govt_effectiveness_orig,political_stability_orig,Law_orig,Voice_Accountability_orig,corruption_dest,govt_effectiveness_dest,political_stability_dest,Law_dest,Voice_Accountability_dest,trade_value
0,1995,840,4,AS,173945233,8528019,7.639749e+12,0.000000e+00,11626.580,5.65,...,-2.17517,-2.41404,-1.78808,-1.90854,1.571041,1.52492,0.935775,1.500219,1.348661,5711.54
1,1995,840,8,EU,173945233,1941355,7.639749e+12,8.497854e+09,8882.747,5.65,...,-0.688588,-0.333811,-0.684482,-0.648298,1.571041,1.52492,0.935775,1.500219,1.348661,10177.9
2,1995,840,12,AF,173945233,16374751,7.639749e+12,1.967952e+11,8125.746,5.65,...,-1.08877,-1.78003,-1.21819,-1.16629,1.571041,1.52492,0.935775,1.500219,1.348661,1.80721e+06
3,1995,840,24,AF,173945233,7081533,7.639749e+12,3.481002e+10,12153.610,5.65,...,-0.85994,-2.05729,-1.63047,-1.57816,1.571041,1.52492,0.935775,1.500219,1.348661,2.39016e+06
4,1995,840,28,NoAm,173945233,45598,7.639749e+12,8.884509e+08,3965.093,5.65,...,0.644922,0.718495,1.05085,0.333532,1.571041,1.52492,0.935775,1.500219,1.348661,3200.54

In [9]:
pairs_2000 = imports_1[imports_1['Year']==2000]['pairs']
trade_value_2000 = imports_1[imports_1['Year']==2000]['trade_value']
trade_value_df2000 = pd.DataFrame({'pairs':pairs_2000, 'trade_value':trade_value_2000})
trade_value_dict2000 = trade_value_df2000.set_index('pairs').to_dict()['trade_value']

a_2000 = a_2000.replace({'trade_value': trade_value_dict2000})
a_2000.head(5)

,Year,code_dest,code_orig,Continent org,Popn des,Popn org,GDP_PPP des,GDP_PPP org,Distance,Emp rate des,...,govt_effectiveness_orig,political_stability_orig,Law_orig,Voice_Accountability_orig,corruption_dest,govt_effectiveness_dest,political_stability_dest,Law_dest,Voice_Accountability_dest,trade_value
0,2000,840,4,AS,186169060,9882514,1.025235e+13,0.000000e+00,11626.580,3.992,...,-2.23165,-2.44019,-1.77844,-2.03142,1.657759,1.802651,1.084508,1.592754,1.310167,780.891
1,2000,840,8,EU,186169060,1935652,1.025235e+13,1.192779e+10,8882.747,3.992,...,-0.755118,-0.537979,-1.00878,-0.285139,1.657759,1.802651,1.084508,1.592754,1.310167,7767.28
2,2000,840,12,AF,186169060,19144447,1.025235e+13,2.533795e+11,8125.746,3.992,...,-0.963841,-1.43201,-1.21134,-1.11005,1.657759,1.802651,1.084508,1.592754,1.310167,2.72427e+06
3,2000,840,24,AF,186169060,8241956,1.025235e+13,5.078182e+10,12153.610,3.992,...,-1.46231,-2.03558,-1.66331,-1.45806,1.657759,1.802651,1.084508,1.592754,1.310167,3.55529e+06
4,2000,840,28,NoAm,186169060,53414,1.025235e+13,1.257640e+09,3965.093,3.992,...,0.658155,0.714189,1.05892,0.390962,1.657759,1.802651,1.084508,1.592754,1.310167,2291.65

Similarly do for the rest of the years

In [ ]:
writer = pd.ExcelWriter('a_95.xlsx', engine='xlsxwriter')
a_95.to_excel(writer, sheet_name='Sheet1')
writer.save()